### ISSUE TITLE
gzip: response headers lack transfer-encoding field when using http.FileServer to transfer file

### ISSUE THREAD

**Issue by parkghost** [streadway/handy#23]
for example
```go
package main

import (
	"net/http"

	"github.com/streadway/handy/encoding"
)

func main() {
	http.Handle("/js/", encoding.Gzip(http.FileServer(http.Dir("public"))))
	http.ListenAndServe(":3000", nil)
}
```
test it with curl
```text
curl -v --compressed http://localhost:3000/js/vendor/modernizr-2.8.3.min.js > /dev/null
* Hostname was NOT found in DNS cache
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 3000 (#0)
> GET /js/vendor/modernizr-2.8.3.min.js HTTP/1.1
> User-Agent: curl/7.35.0
> Host: localhost:3000
> Accept: */*
> Accept-Encoding: deflate, gzip
> 
< HTTP/1.1 200 OK
< Accept-Ranges: bytes
< Content-Length: 15514
< Content-Type: application/javascript
< Date: Fri, 06 Mar 2015 20:47:06 GMT
< Last-Modified: Mon, 02 Feb 2015 11:08:36 GMT
< 
{ [data not shown]
* transfer closed with 9204 bytes remaining to read
 40 15514   40  6310    0     0  23210      0 --:--:-- --:--:-- --:--:-- 23284
* Closing connection 0
curl: (18) transfer closed with 9204 bytes remaining to read
```

**Comment by telendt** [comment]
Transfer encoding is missing because `FileServer` calls `WriteHeader` (when `ServeHTTP`) which flushes all headers and prevents `gzipWriter` from settings its headers (at first `Write` call). 
This is not the only problem here - the other is `Content-Length` value which `http.FileServer` sets as the size of the uncompressed file. HTTP client gets less bytes than expected and freaks out.

It can by fixed by setting headers **before** letting `FileServer` call `ServeHTTP`:

	package main

	import (
		"net/http"
		"github.com/streadway/handy/encoding"
	)

	func setHeaders(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			w.Header().Set("Content-Encoding", "gzip")
			w.Header().Set("Transfer-Encoding", "chunked")
			next.ServeHTTP(w, r)
		})
	}

	func main() {
		http.Handle("/", encoding.Gzip(setHeaders(http.FileServer(http.Dir(".")))))
		http.ListenAndServe(":3000", nil)
	}

This works because [`FileServer` doesn't send `Content-Length` if `Content-Encoding` is specified](http://golang.org/src/net/http/fs.go#L249).

I believe that `encoding.gzip` could play nice with `FileServer` but it would need to override `WriteHeader` method as well.
